version: "3.9"

services:
  postgres_raw:
    image: postgres:15
    container_name: postgres_raw
    environment:
      POSTGRES_DB: raw_db
      POSTGRES_USER: raw_user
      POSTGRES_PASSWORD: raw_password
    command: >
      postgres
      -c wal_level=logical
      -c max_wal_senders=10
      -c max_replication_slots=10
    ports:
      - "5432:5432"
    volumes:
      - raw_pg_data:/var/lib/postgresql/data
      - ./init/raw_postgres:/docker-entrypoint-initdb.d
    networks:
      - de-net

  postgres_dwh:
    image: postgres:15
    container_name: postgres_dwh
    environment:
      POSTGRES_DB: dwh_db
      POSTGRES_USER: dwh_user
      POSTGRES_PASSWORD: dwh_password
    ports:
      - "5434:5432"
    volumes:
      - dwh_pg_data:/var/lib/postgresql/data
      - ./init/dwh_postgres:/docker-entrypoint-initdb.d
    networks:
      - de-net

  zookeeper-1:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: zookeeper-1
    hostname: zookeeper-1
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: "zookeeper-1:2888:3888;zookeeper-2:2888:3888;zookeeper-3:2888:3888"
    ports:
      - "2181:2181"
    volumes:
      - zookeeper_data_1:/var/lib/zookeeper/data
    networks:
      - de-net

  zookeeper-2:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: zookeeper-2
    hostname: zookeeper-2
    environment:
      ZOOKEEPER_SERVER_ID: 2
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: "zookeeper-1:2888:3888;zookeeper-2:2888:3888;zookeeper-3:2888:3888"
    ports:
      - "2182:2181"
    volumes:
      - zookeeper_data_2:/var/lib/zookeeper/data
    networks:
      - de-net

  zookeeper-3:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: zookeeper-3
    hostname: zookeeper-3
    environment:
      ZOOKEEPER_SERVER_ID: 3
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: "zookeeper-1:2888:3888;zookeeper-2:2888:3888;zookeeper-3:2888:3888"
    ports:
      - "2183:2181"
    volumes:
      - zookeeper_data_3:/var/lib/zookeeper/data
    networks:
      - de-net

  kafka-broker-1:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka-broker-1
    depends_on:
      zookeeper-1:
        condition: service_started
      zookeeper-2:
        condition: service_started
      zookeeper-3:
        condition: service_started
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker-1:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_MIN_INSYNC_REPLICAS: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    healthcheck:
      test: ["CMD", "bash", "-lc", "kafka-topics --bootstrap-server localhost:29092 --list >/dev/null 2>&1"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - kafka_data_1:/var/lib/kafka/data
    networks:
      - de-net

  kafka-broker-2:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka-broker-2
    depends_on:
      zookeeper-1:
        condition: service_started
      zookeeper-2:
        condition: service_started
      zookeeper-3:
        condition: service_started
    ports:
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker-2:29092,PLAINTEXT_HOST://localhost:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_MIN_INSYNC_REPLICAS: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    healthcheck:
      test: ["CMD", "bash", "-lc", "kafka-topics --bootstrap-server localhost:29092 --list >/dev/null 2>&1"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - kafka_data_2:/var/lib/kafka/data
    networks:
      - de-net

  kafka-broker-3:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka-broker-3
    depends_on:
      zookeeper-1:
        condition: service_started
      zookeeper-2:
        condition: service_started
      zookeeper-3:
        condition: service_started
    ports:
      - "9094:9094"
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker-3:29092,PLAINTEXT_HOST://localhost:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_MIN_INSYNC_REPLICAS: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    healthcheck:
      test: ["CMD", "bash", "-lc", "kafka-topics --bootstrap-server localhost:29092 --list >/dev/null 2>&1"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - kafka_data_3:/var/lib/kafka/data
    networks:
      - de-net

  schema-registry:
    image: confluentinc/cp-schema-registry:7.6.1
    container_name: schema-registry
    depends_on:
      kafka-broker-1:
        condition: service_healthy
      kafka-broker-2:
        condition: service_healthy
      kafka-broker-3:
        condition: service_healthy
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_LISTENERS: "http://0.0.0.0:8081"
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: "PLAINTEXT://kafka-broker-1:29092,PLAINTEXT://kafka-broker-2:29092,PLAINTEXT://kafka-broker-3:29092"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://schema-registry:8081/subjects"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      de-net:
        aliases:
          - schema-registry

  kafka-connect:
    build:
      context: ./connect-image
      dockerfile: Dockerfile
    image: my-debezium-connect:3.3
    container_name: kafka-connect
    depends_on:
      kafka-broker-1:
        condition: service_healthy
      kafka-broker-2:
        condition: service_healthy
      kafka-broker-3:
        condition: service_healthy
      schema-registry:
        condition: service_healthy
      postgres_raw:
        condition: service_started
      postgres_dwh:
        condition: service_started
    ports:
      - "8083:8083"
    environment:
      BOOTSTRAP_SERVERS: "kafka-broker-1:29092,kafka-broker-2:29092,kafka-broker-3:29092"
      GROUP_ID: "connect-cluster"
      CONFIG_STORAGE_TOPIC: "connect-configs"
      OFFSET_STORAGE_TOPIC: "connect-offsets"
      STATUS_STORAGE_TOPIC: "connect-status"
      CONFIG_STORAGE_REPLICATION_FACTOR: "1"
      OFFSET_STORAGE_REPLICATION_FACTOR: "1"
      STATUS_STORAGE_REPLICATION_FACTOR: "1"
      KEY_CONVERTER: "io.confluent.connect.avro.AvroConverter"
      VALUE_CONVERTER: "io.confluent.connect.avro.AvroConverter"
      KEY_CONVERTER_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
      VALUE_CONVERTER_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
      REST_PORT: "8083"
      REST_ADVERTISED_HOST_NAME: "kafka-connect"
      KAFKA_CONNECT_PLUGINS_DIR: "/kafka/connect"
    restart: unless-stopped
    networks:
      - de-net

  kafka-ui:
    image: ghcr.io/kafbat/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      kafka-broker-1:
        condition: service_healthy
      kafka-broker-2:
        condition: service_healthy
      kafka-broker-3:
        condition: service_healthy
      schema-registry:
        condition: service_started
    ports:
      - "9000:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka-broker-1:29092,kafka-broker-2:29092,kafka-broker-3:29092"
      KAFKA_CLUSTERS_0_SCHEMAREGISTRY: "http://schema-registry:8081"
    networks:
      - de-net

  greenplum:
    image: pro100filipp/greenplum-with-pxf
    container_name: greenplum
    environment:
      GP_DB: gpdb
      GP_USER: gpadmin
      GP_PASSWORD: gpadmin
    ports:
      - "5435:5432"
    volumes:
      - gp_data:/srv
      - ./init/greenplum:/docker-entrypoint-initdb.d
    networks:
      - de-net

  airflow-db:
    image: postgres:15
    container_name: airflow-db
    environment:
      POSTGRES_DB: airflow
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
    volumes:
      - airflow_db_data:/var/lib/postgresql/data
    networks:
      - de-net

  airflow-webserver:
    image: apache/airflow:2.9.2
    container_name: airflow-webserver
    depends_on:
      airflow-db:
        condition: service_started
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-db/airflow
      AIRFLOW__CORE__FERNET_KEY: HqQy5Jzi10BGSAdoo6gWQBaIjXImQxGc1dQc5sKXc5s=
      AIRFLOW__WEBSERVER__DEFAULT_UI_TIMEZONE: "Europe/Moscow"
      _AIRFLOW_WWW_USER_USERNAME: admin
      _AIRFLOW_WWW_USER_PASSWORD: admin
      AIRFLOW_UID: "50000"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
    command: webserver
    ports:
      - "8080:8080"
    networks:
      - de-net

  airflow-scheduler:
    image: apache/airflow:2.9.2
    container_name: airflow-scheduler
    depends_on:
      airflow-db:
        condition: service_started
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-db/airflow
      AIRFLOW__CORE__FERNET_KEY: HqQy5Jzi10BGSAdoo6gWQBaIjXImQxGc1dQc5sKXc5s=
      AIRFLOW__WEBSERVER__DEFAULT_UI_TIMEZONE: "Europe/Moscow"
      AIRFLOW_UID: "50000"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
    command: scheduler
    networks:
      - de-net

networks:
  de-net:
    driver: bridge

volumes:
  raw_pg_data:
  dwh_pg_data:
  airflow_db_data:
  kafka_data_1:
  kafka_data_2:
  kafka_data_3:
  zookeeper_data_1:
  zookeeper_data_2:
  zookeeper_data_3:
  gp_data:
