version: "3.9"

services:
  postgres_raw:
    image: postgres:15
    container_name: postgres_raw
    environment:
      POSTGRES_DB: raw_db
      POSTGRES_USER: raw_user
      POSTGRES_PASSWORD: raw_password
    command: >
      postgres
      -c wal_level=logical
      -c max_wal_senders=10
      -c max_replication_slots=10
    ports:
      - "5432:5432"
    volumes:
      - raw_pg_data:/var/lib/postgresql/data
      - ./init/raw_postgres:/docker-entrypoint-initdb.d
    networks:
      - de-net

  postgres_dwh:
    image: postgres:15
    container_name: postgres_dwh
    environment:
      POSTGRES_DB: dwh_db
      POSTGRES_USER: dwh_user
      POSTGRES_PASSWORD: dwh_password
    ports:
      - "5434:5432"
    volumes:
      - dwh_pg_data:/var/lib/postgresql/data
      - ./init/dwh_postgres:/docker-entrypoint-initdb.d
    networks:
      - de-net

  trino:
    image: trinodb/trino:443
    container_name: trino
    depends_on:
      - greenplum
    ports:
      - "8085:8080"
    volumes:
      - ./trino/etc/catalog:/etc/trino/catalog
    environment:
      TZ: Europe/Moscow
    networks:
      - de-net

  superset:
    build:
      context: .
      dockerfile: Dockerfile.superset
    container_name: superset
    restart: unless-stopped
    ports:
      - "8088:8088"
    depends_on:
      - trino
    environment:
      SUPERSET_HOME: /app/superset_home
      SUPERSET_SECRET_KEY: "change_me_please_123"
      SUPERSET_LOAD_EXAMPLES: "no"
      SUPERSET_ADMIN_USERNAME: "admin"
      SUPERSET_ADMIN_FIRST_NAME: "Admin"
      SUPERSET_ADMIN_LAST_NAME: "User"
      SUPERSET_ADMIN_EMAIL: "admin@example.com"
      SUPERSET_ADMIN_PASSWORD: "admin"
    volumes:
      - ./superset_home:/app/superset_home
    command: >
      /bin/bash -c "
      superset db upgrade &&
      superset init &&
      superset run -p 8088 --host 0.0.0.0
      "
    networks:
      - de-net

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    healthcheck:
      test: [ "CMD", "bash", "-lc", "echo srvr | nc localhost 2181 | grep Mode" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - zookeeper_data:/var/lib/zookeeper/data
    networks:
      - de-net

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_MIN_INSYNC_REPLICAS: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    healthcheck:
      test: ["CMD", "bash", "-lc", "kafka-topics --bootstrap-server localhost:29092 --list >/dev/null 2>&1"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - de-net

  schema-registry:
    image: confluentinc/cp-schema-registry:7.6.1
    container_name: schema-registry
    depends_on:
      kafka:
        condition: service_healthy
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_LISTENERS: "http://0.0.0.0:8081"
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: "PLAINTEXT://kafka:29092"
    networks:
      - de-net

  kafka-connect:
    build:
      context: ./connect-image
      dockerfile: Dockerfile
    image: my-debezium-connect:3.3
    container_name: kafka-connect
    depends_on:
      kafka:
        condition: service_healthy
      schema-registry:
        condition: service_started
      postgres_raw:
        condition: service_started
      postgres_dwh:
        condition: service_started
    ports:
      - "8083:8083"
    environment:
      BOOTSTRAP_SERVERS: "kafka:29092"
      GROUP_ID: "connect-cluster"

      CONFIG_STORAGE_TOPIC: "connect-configs"
      OFFSET_STORAGE_TOPIC: "connect-offsets"
      STATUS_STORAGE_TOPIC: "connect-status"

      CONFIG_STORAGE_REPLICATION_FACTOR: "1"
      OFFSET_STORAGE_REPLICATION_FACTOR: "1"
      STATUS_STORAGE_REPLICATION_FACTOR: "1"

      KEY_CONVERTER: "io.confluent.connect.avro.AvroConverter"
      VALUE_CONVERTER: "io.confluent.connect.avro.AvroConverter"
      KEY_CONVERTER_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
      VALUE_CONVERTER_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"

      REST_PORT: "8083"
      REST_ADVERTISED_HOST_NAME: "kafka-connect"

      KAFKA_CONNECT_PLUGINS_DIR: "/kafka/connect"
    restart: unless-stopped
    networks:
      - de-net

  kafka-ui:
    image: ghcr.io/kafbat/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      kafka:
        condition: service_healthy
      schema-registry:
        condition: service_started
    ports:
      - "9000:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: "local"
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka:29092"
      KAFKA_CLUSTERS_0_SCHEMAREGISTRY: "http://schema-registry:8081"
    networks:
      - de-net

  greenplum:
    image: pro100filipp/greenplum-with-pxf
    container_name: greenplum
    hostname: greenplum
    environment:
      GP_DB: gpdb
      GP_USER: gpadmin
      GP_PASSWORD: gpadmin
    ports:
      - "5435:5432"
    volumes:
      - gp_data:/srv
      - ./init/greenplum:/docker-entrypoint-initdb.d
    networks:
      - de-net

  airflow-db:
    image: postgres:15
    container_name: airflow-db
    environment:
      POSTGRES_DB: airflow
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
    volumes:
      - airflow_db_data:/var/lib/postgresql/data
    networks:
      - de-net

  airflow-webserver:
    image: apache/airflow:2.9.2
    container_name: airflow-webserver
    depends_on:
      airflow-db:
        condition: service_started
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-db/airflow
      AIRFLOW__CORE__FERNET_KEY: HqQy5Jzi10BGSAdoo6gWQBaIjXImQxGc1dQc5sKXc5s=
      AIRFLOW__WEBSERVER__DEFAULT_UI_TIMEZONE: "Europe/Moscow"
      _AIRFLOW_WWW_USER_USERNAME: admin
      _AIRFLOW_WWW_USER_PASSWORD: admin
      AIRFLOW_UID: "50000"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
    command: webserver
    ports:
      - "8080:8080"
    networks:
      - de-net

  airflow-scheduler:
    image: apache/airflow:2.9.2
    container_name: airflow-scheduler
    depends_on:
      airflow-db:
        condition: service_started
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-db/airflow
      AIRFLOW__CORE__FERNET_KEY: HqQy5Jzi10BGSAdoo6gWQBaIjXImQxGc1dQc5sKXc5s=
      AIRFLOW__WEBSERVER__DEFAULT_UI_TIMEZONE: "Europe/Moscow"
      AIRFLOW_UID: "50000"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
    command: scheduler
    networks:
      - de-net

networks:
  de-net:
    driver: bridge

volumes:
  raw_pg_data:
  dwh_pg_data:
  airflow_db_data:
  kafka_data:
  zookeeper_data:
  gp_data:
